

# --------------------------------
# BASE

server:
  port: 17087
  servlet.context-path: /v0.5


spring:
  profiles.active:
  - proj-default
  - proj-local
  #- proj-test
  #- proj-aws
  #- proj-dfep
  #- proj-real
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/sentbedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.time-zone: UTC+9
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: true


logging:
  file:
    path: logs/mapper/
    max-size: 10MB
    max-history: 30         # delete after a month
  pattern:
    console: "%clr(%d{HH:mm:ss} %p){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info
    
    #org.tain.utils.TransferStrAndJson: trace


---
# --------------------------------------------------------
spring.profiles: proj-default

proj-env:
  base:
    name: Sentbe API project
    program: KieaSentbe API program
    version: ver 0.5_2020.09.23
    comment: This is Sentbe API project.

  param:
    name: PARAM (default)

  job:
    name: JOB (default)

  json:
    name: JSON (default)

  url:
    name: URL (default)

---
# --------------------------------------------------------
# proj-local
spring.profiles: proj-local

proj-env:

  param:
    name: PARAM (local)

  job:
    name: JOB (local)

  json:
    name: JSON (local)

  url:
    name: URL (local)

---
# --------------------------------------------------------
# proj-test
spring.profiles: proj-test

proj-env:

  param:
    name: PARAM (test)

  job:
    name: JOB (test)

  json:
    name: JSON (test)

  url:
    name: URL (test)

---
# --------------------------------------------------------
# proj-aws
spring.profiles: proj-aws

proj-env:

  param:
    name: PARAM (aws)

  job:
    name: JOB (aws)

  json:
    name: JSON (aws)

  url:
    name: URL (aws)

---
# --------------------------------------------------------
# proj-dfep
spring.profiles: proj-dfep

proj-env:

  param:
    name: PARAM (dfep)

  job:
    name: JOB (dfep)

  json:
    name: JSON (dfep)

  url:
    name: URL (dfep)

---
# --------------------------------------------------------
# proj-real
spring.profiles: proj-real

proj-env:

  param:
    name: PARAM (real)

  job:
    name: JOB (real)

  json:
    name: JSON (real)

  url:
    name: URL (real)


